project_id = "bwvocmhcledbwqlpcswp"

[functions.recording-status-callback]
verify_jwt = false

[functions.generate-api-key]
verify_jwt = false

[functions.process-expiry-notifications]
verify_jwt = false

[functions.whatsapp-commands]
verify_jwt = false

[functions.process-predue-reminders]
verify_jwt = false

[functions.process-payment-unlock]
verify_jwt = false

[functions.twilio-webhook]
verify_jwt = false

[functions.voip-status-callback]
verify_jwt = false

[functions.email-webhook]
verify_jwt = false

[functions.send-2fa-code]
verify_jwt = false

[functions.generate-daily-tasks]
verify_jwt = false

[functions.voice-call-request]
verify_jwt = false

[functions.payment-default-ivr]
verify_jwt = false