import { SentTemplate } from "./types";

export const DEFAULT_SENT_TEMPLATES: SentTemplate[] = [
  {
    id: "rentmaikar_payment_reminder",
    name: "Payment Reminder (Pre-Due)",
    channel: "sms",
    category: "transactional",
    body: "Hi {firstName}, your {frequency} payment of {amount} is due tomorrow. Ensure your account is funded to avoid service interruption. – Rentmaikar",
    parameters: ["firstName", "frequency", "amount"],
    language: "en",
    status: "approved",
  },
  {
    id: "rentmaikar_payment_default",
    name: "Payment Default Alert (Overdue)",
    channel: "sms",
    category: "alerts",
    body: "URGENT: Your payment of {amount} is {hoursOverdue}h overdue. Vehicle deactivation may occur. Pay now or call support: {supportNumber}. – Rentmaikar",
    parameters: ["amount", "hoursOverdue", "supportNumber"],
    language: "en",
    status: "approved",
  },
  {
    id: "rentmaikar_2fa_otp",
    name: "2FA Verification Code",
    channel: "sms",
    category: "otp",
    body: "Your Rentmaikar verification code is {code}. Expires in 5 minutes. Do not share this code with anyone.",
    parameters: ["code"],
    language: "en",
    status: "approved",
  },
  {
    id: "rentmaikar_whatsapp_booking_confirm",
    name: "WhatsApp Rental Confirmation",
    channel: "whatsapp",
    category: "transactional",
    body: "Hello {firstName}! 🚗 Your rental of {vehicleName} ({vehiclePlate}) has been confirmed. Pickup point: {pickupLocation} at {pickupTime}. Reply HELP for assistance.",
    parameters: ["firstName", "vehicleName", "vehiclePlate", "pickupLocation", "pickupTime"],
    language: "en",
    status: "approved",
  },
  {
    id: "rentmaikar_rcs_incident_alert",
    name: "RCS Incident & Safety Notification",
    channel: "rcs",
    category: "alerts",
    body: "⚠️ Rentmaikar Safety Alert: Vehicle {vehiclePlate} report logged at {location}. Response team dispatched. Follow instructions in your driver app.",
    parameters: ["vehiclePlate", "location"],
    language: "en",
    status: "approved",
  },
  {
    id: "rentmaikar_vehicle_return",
    name: "Vehicle Return Notice (24h)",
    channel: "sms",
    category: "transactional",
    body: "Hi {firstName}, your vehicle ({vehicleName}) is due for return tomorrow at {returnTime}. Reply CONFIRM to acknowledge or EXTEND to request an extension.",
    parameters: ["firstName", "vehicleName", "returnTime"],
    language: "en",
    status: "approved",
  },
];
