import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  useCallback,
  useRef,
  ReactNode,
} from "react";
import { DollarSign } from "lucide-react";
import { detectCountryFromIP, detectCountryFromTimezone } from "@/lib/ip-geolocation";
import { supabase } from "@/integrations/supabase/client";
import {
  BUILTIN_REGION_OPTIONS,
  mergeRegions,
  mapAllowedRegionRows,
  readRegionCache,
  writeRegionCache,
  clearRegionCache,
  resolveRegion,
  type AllowedRegionRow,
} from "@/lib/region-cache";
import {
  regionConfig,
  contactOverrides,
  companyInfoMap,
} from "@/lib/region-config";
import {
  getStoredCountry,
  getStoredMode,
  persistCountry,
  persistMode,
} from "@/lib/region-cookie";

/**
 * Regions are no longer a closed set. "USA" and "Nigeria" are the built-in
 * launch regions; every other region is generated by the admin Region Builder
 * (public.region_definitions) and becomes selectable once it is ready or
 * published. The `(string & {})` branch keeps literal autocomplete for the
 * built-ins while allowing any builder-generated country name.
 */
export type Country = "USA" | "Nigeria" | (string & {});
export type RegionMode = "auto" | "manual";
export type Currency = "USD" | "NGN" | (string & {});

export const BUILTIN_COUNTRIES = ["USA", "Nigeria"] as const;

export interface RegionOption {
  /** Canonical country value used across the app (matches region_definitions.country_name). */
  value: Country;
  label: string;
  flag: string;
  countryCode: string;
  currency: Currency;
  currencySymbol: string;
  phonePrefix: string;
  /** True for the two hard-coded launch regions. */
  builtIn: boolean;
}

export interface CompanyInfo {
  companyName: string;
  phone: string;
  phoneRaw: string;
  email: string;
  fullAddress: string;
  address: string;
  city: string;
  state: string;
  country: string;
  postalCode: string;
}

export interface RegionConfig {
  currency: Currency;
  currencySymbol: string;
  phonePrefix: string;
  whatsappNumber: string;
  smsNumber: string;
  supportEmail: string;
}

interface RegionContextType {
  country: Country;
  setCountry: (country: Country) => void;
  regionMode: RegionMode;
  setRegionMode: (mode: RegionMode) => void;
  isDetecting: boolean;
  currency: Currency;
  currencySymbol: string;
  phonePrefix: string;
  whatsappNumber: string;
  smsNumber: string;
  supportEmail: string;
  companyInfo: CompanyInfo | null;
  getCurrencyIcon: (className?: string) => React.ReactNode;
  config: RegionConfig;
  /** Built-in regions + every Region Builder region that is ready/published. */
  availableRegions: RegionOption[];
  regionsLoading: boolean;
  /** Freshness of the region list so the UI can flag cached/offline data. */
  regionSync: RegionSyncState;
  /** Force a re-fetch of the allowed-region list (bypasses the offline cache). */
  refreshRegions: () => Promise<void>;
}

export interface RegionSyncState {
  /** Where the currently rendered region list came from. */
  source: "live" | "cache" | "builtin";
  /** Epoch ms of the last successful server sync (null when never synced). */
  lastSyncedAt: number | null;
  /** Cache is older than the TTL, or the last refresh attempt failed. */
  stale: boolean;
  /** Browser reports no connectivity, or the last fetch failed while offline. */
  offline: boolean;
  /** A manual/automatic refresh is currently in flight. */
  refreshing: boolean;
}



// Base config (currency + phone prefix only). Contact channels — WhatsApp, SMS,
// and support email — are loaded from the admin-managed Regional Contact
// Channels table (public.contact_settings). Empty strings here mean
// "not yet loaded"; consumers should render conditionally.


// Built-in launch regions live in region-cache so both the cache layer and the
// provider agree on the guaranteed-available baseline.
export { BUILTIN_REGION_OPTIONS };




const stripPhone = (v: string) => (v || "").replace(/[^\d]/g, "");

const NairaIcon = ({ className }: { className?: string }) => (
  <span className={className} aria-hidden>₦</span>
);

const RegionContext = createContext<RegionContextType | undefined>(undefined);

const SAFE_DEFAULT: Country = "USA";

export const RegionProvider = ({ children }: { children: ReactNode }) => {
  const [isDetecting, setIsDetecting] = useState(false);

  const [regionMode, setRegionModeState] = useState<RegionMode>(
    () => getStoredMode() ?? "auto"
  );

  const [country, setCountryState] = useState<Country>(() => {
    const stored = getStoredCountry();
    if (stored) return stored;
    try {
      return detectCountryFromTimezone();
    } catch {
      return SAFE_DEFAULT;
    }
  });

// ---------------------------------------------------------------------
// Ensure the currently selected region is still valid.
// If an admin unpublishes a region, automatically fall back to SAFE_DEFAULT.
// ---------------------------------------------------------------------



  
/**
 * Switch region. The value is resolved against the allow-list first, then
 * persisted server-side through `set_my_region` so web and mobile read the
 * same source of truth after login. The server re-validates and rejects any
 * region the user is not permitted to select.
 */


  // Guards that keep the switcher stable: once the user picks a region we
  // never let auto-detection or a profile re-sync overwrite that choice.
  // The manual flag is persisted so it also survives reloads.
  const manualSelectRef = useRef(getManualPick());
  const autoDetectedRef = useRef(getManualPick());
  const syncedUserRef = useRef<string | null>(null);

  const setCountry = (next: Country) => {
  if (regionsLoading) return;

  const resolved = resolveRegion(next, availableRegions);

  if (!resolved) return;

  manualSelectRef.current = true;
  autoDetectedRef.current = true;
  persistManualPick(true);

  setRegionModeState("manual");
  persistMode("manual");

  setCountryState(resolved.value);
  persistCountry(resolved.value);

  void supabase.rpc("set_my_region", {
    _country: resolved.value,
  });
};



// ---------------------------------------------------------------------
// Region Builder regions. The two built-ins are always available; every
// region generated by the admin Region Builder joins the list once it is
// published and updates automatically.
// ---------------------------------------------------------------------

// Seed from the offline cache so the PWA can render immediately.
const [builderRegions, setBuilderRegions] = useState<RegionOption[]>(
  () => readRegionCache()?.regions.filter((r) => !r.builtIn) ?? []
);

const availableRegions = React.useMemo(
  () => mergeRegions(builderRegions),
  [builderRegions]
);

const [regionsLoading, setRegionsLoading] = useState(
  () => !readRegionCache()
);


const setRegionMode = (next: RegionMode) => {
  setRegionModeState(next);
  persistMode(next);
};

  const selectedRegion =
  availableRegions.find(r => r.value === country) ?? null;


// First-load auto detection (IP -> timezone -> safe default)
useEffect(() => {
  let cancelled = false;

  const run = async () => {
    if (regionMode !== "auto") return;

    // Wait until the allowed region list has loaded.
    if (regionsLoading) return;

    // Detect once per session, and never after a manual selection.
    if (autoDetectedRef.current || manualSelectRef.current) return;
    autoDetectedRef.current = true;

    setIsDetecting(true);


    try {
      const result = await detectCountryFromIP();

      if (!cancelled && result.detected) {
        // Only allow published/available regions.
        const resolved = resolveRegion(
          result.country,
          availableRegions
        );

        const selected = resolved?.value ?? SAFE_DEFAULT;

        setCountryState(selected);
        persistCountry(selected);
      }
    } catch {
      // Keep timezone/stored/default fallback.
    } finally {
      if (!cancelled) {
        setIsDetecting(false);
      }
    }
  };

  run();

  return () => {
    cancelled = true;
  };
}, [regionMode, regionsLoading, availableRegions]);
     
// Sync with the signed-in user's profile preference.
// Owners/drivers (and any non-admin role) are locked to their registration
// region. Only admins and admin assistants may freely switch regions.
useEffect(() => {
  if (regionsLoading) return;

  let cancelled = false;

  const syncProfile = async (userId: string) => {
    // Only sync once per signed-in user — re-running on every region change
    // made the admin switcher snap back to the stored profile value.
    if (syncedUserRef.current === userId) return;
    syncedUserRef.current = userId;
    try {

      const [{ data: profile }, { data: roles }] = await Promise.all([
        supabase
          .from("profiles")
          .select("preferred_country, region_mode")
          .eq("user_id", userId)
          .maybeSingle(),

        supabase
          .from("user_roles")
          .select("role")
          .eq("user_id", userId),
      ]);

      if (cancelled) return;

      const roleList = (roles ?? []).map(
        (r: { role: string }) => r.role
      );

      const isAdminLike =
        roleList.includes("admin") ||
        roleList.includes("admin_assistant");

      const profileCountry =
        (profile?.preferred_country ?? null) as Country | null;

      const profileMode =
        (profile?.region_mode ?? null) as RegionMode | null;

      // Validate the stored country against the published region list.
      const resolved = profileCountry
        ? resolveRegion(profileCountry, availableRegions)
        : null;

      // ------------------------------------------------------------------
      // Owners / Drivers / Customers
      // ------------------------------------------------------------------
      if (!isAdminLike) {
        let lockedCountry =
          resolved?.value ??
          getStoredCountry() ??
          SAFE_DEFAULT;

        setRegionModeState("manual");
        persistMode("manual");

        setCountryState(lockedCountry);
        persistCountry(lockedCountry);

        // First sign-in or unpublished region -> repair profile.
        if (
          !profileCountry ||
          profileCountry !== lockedCountry
        ) {
          void supabase
            .from("profiles")
            .update({
              preferred_country: lockedCountry,
              region_mode: "manual",
            })
            .eq("user_id", userId);
        }

        return;
      }

      // ------------------------------------------------------------------
      // Admin / Admin Assistant — free to switch; never override a choice
      // the admin has already made in this session.
      // ------------------------------------------------------------------

      if (manualSelectRef.current) return;

      if (profileMode === "auto" || profileMode === "manual") {
        setRegionModeState(profileMode);
        persistMode(profileMode);
      }

      if (resolved) {
        autoDetectedRef.current = true;
        setCountryState(resolved.value);
        persistCountry(resolved.value);
      } else if (profileMode === "manual") {
        setCountryState(SAFE_DEFAULT);
        persistCountry(SAFE_DEFAULT);
      }

    } catch (error) {
      console.warn("[region] profile sync failed", error);
    }
  };

  void supabase.auth.getUser().then(({ data }) => {
    if (data.user) {
      void syncProfile(data.user.id);
    }
  });

  const {
    data: { subscription },
  } = supabase.auth.onAuthStateChange((_event, session) => {

    if (session?.user) {
      void syncProfile(session.user.id);
    } else {
      // Signed out: allow the next user to sync fresh.
      syncedUserRef.current = null;
      manualSelectRef.current = false;
    }
  });

  return () => {
    cancelled = true;
    subscription.unsubscribe();
  };
}, [availableRegions, regionsLoading]);



// Persist manual selections back to the user's profile.
useEffect(() => {
  if (regionMode !== "manual") return;

  void supabase.auth.getUser().then(({ data }) => {
    if (!data.user) return;

    void supabase
      .from("profiles")
      .update({
        preferred_country: country,
        region_mode: "manual",
      })
      .eq("user_id", data.user.id);
  });
}, [country, regionMode]);

// Ensure the currently selected region is still valid.
// This protects against regions being unpublished or removed.
useEffect(() => {
  if (regionsLoading) return;

   const resolved = resolveRegion(
    country,
    availableRegions
  );

  if (!resolved) {
    setCountryState(SAFE_DEFAULT);
    persistCountry(SAFE_DEFAULT);
    return;
  }

  if (resolved.value !== country) {
    setCountryState(resolved.value);
    persistCountry(resolved.value);
  }
}, [
  availableRegions,
  country,
  regionsLoading,
]);

  
const [regionSync, setRegionSync] = useState<RegionSyncState>(() => {
  const cached = readRegionCache();

  return {
    source: cached ? "cache" : "builtin",
    lastSyncedAt: cached?.savedAt ?? null,
    stale: cached ? cached.stale : true,
    offline:
      typeof navigator !== "undefined"
        ? !navigator.onLine
        : false,
    refreshing: false,
  };
});

const cancelledRef = useRef(false);
useEffect(() => {
  cancelledRef.current = false;

  return () => {
    cancelledRef.current = true;
  };
}, []);

const loadRegions = useCallback(async () => {
  setRegionSync((prev) => ({
    ...prev,
    refreshing: true,
  }));

  try {
    const { data, error } =
      await supabase.rpc("get_allowed_regions");

    if (cancelledRef.current) return;

    if (error || !data) {
      setRegionSync((prev) => ({
        ...prev,
        stale: true,
        offline:
          typeof navigator !== "undefined"
            ? !navigator.onLine
            : false,
        refreshing: false,
      }));

      setRegionsLoading(false);
      return;
    }

    const mapped = mapAllowedRegionRows(
      data as AllowedRegionRow[]
    );

    const builderOnly = mapped.filter(
      (r) => !r.builtIn
    );

    setBuilderRegions(builderOnly);

    writeRegionCache(
      mergeRegions(builderOnly)
    );

    setRegionSync({
      source: "live",
      lastSyncedAt: Date.now(),
      stale: false,
      offline: false,
      refreshing: false,
    });
  } catch {
    if (cancelledRef.current) return;

    setRegionSync((prev) => ({
      ...prev,
      stale: true,
      offline:
        typeof navigator !== "undefined"
          ? !navigator.onLine
          : false,
      refreshing: false,
    }));
  } finally {
    if (!cancelledRef.current) {
      setRegionsLoading(false);
    }
  }
}, []);

const refreshRegions = useCallback(async () => {
  clearRegionCache();
  await loadRegions();
}, [loadRegions]);

useEffect(() => {
  void loadRegions();

  const channel = supabase
    .channel("region_definitions_available")
    .on(
      "postgres_changes",
      {
        event: "*",
        schema: "public",
        table: "region_definitions",
      },
      () => {
        void loadRegions();
      }
    )
    .subscribe();

  const onResume = () => {
    if (document.visibilityState === "visible") {
      void loadRegions();
    }
  };

  const onOnline = () => {
    void loadRegions();
  };

  const onOffline = () => {
    setRegionSync((prev) => ({
      ...prev,
      offline: true,
      stale: true,
    }));
  };

  document.addEventListener(
    "visibilitychange",
    onResume
  );

  window.addEventListener("online", onOnline);
  window.addEventListener("offline", onOffline);

  const poll = window.setInterval(() => {
    void loadRegions();
  }, 10 * 60 * 1000);

  return () => {
    supabase.removeChannel(channel);

    document.removeEventListener(
      "visibilitychange",
      onResume
    );

    window.removeEventListener(
      "online",
      onOnline
    );

    window.removeEventListener(
      "offline",
      onOffline
    );

    window.clearInterval(poll);
  };
}, [loadRegions]);




// ---------------------------------------------------------------------
// Resolve the active region from the published region list.
// ---------------------------------------------------------------------

// Base configuration.
// Built-in regions use region-config.
// Region Builder regions use their published metadata.
const baseConfig: RegionConfig =
  regionConfig[country] ??
  {
    currency: selectedRegion?.currency ?? "USD",
    currencySymbol: selectedRegion?.currencySymbol ?? "$",

    // Never assume +1 unless the selected region actually uses it.
    phonePrefix: selectedRegion?.phonePrefix ?? "",

    whatsappNumber: "",
    smsNumber: "",
    supportEmail: "",
  };

// Contact overrides loaded from Regional Contact Channels.
const overrides = contactOverrides[country] ?? {};

const config: RegionConfig = {
  ...baseConfig,

  whatsappNumber:
    overrides.whatsappNumber ??
    baseConfig.whatsappNumber,

  smsNumber:
    overrides.smsNumber ??
    baseConfig.smsNumber,

  supportEmail:
    overrides.supportEmail ??
    baseConfig.supportEmail,
};

// ---------------------------------------------------------------------
// Currency icon
// ---------------------------------------------------------------------
const getCurrencyIcon = (className = "h-4 w-4") => {
  switch (config.currency) {
    case "NGN":
      return <NairaIcon className={className} />;

    default:
      return <DollarSign className={className} />;
  }
};

return (
  <RegionContext.Provider
    value={{
      country,
      setCountry,

      regionMode,
      setRegionMode,

      isDetecting,

      currency: config.currency,
      currencySymbol: config.currencySymbol,
      phonePrefix: config.phonePrefix,
      whatsappNumber: config.whatsappNumber,
      smsNumber: config.smsNumber,
      supportEmail: config.supportEmail,

      companyInfo:
        companyInfoMap[country] ?? null,

      getCurrencyIcon,

      config,

      availableRegions,
      regionsLoading,
      regionSync,
      refreshRegions,
    }}
  >
    {children}
  </RegionContext.Provider>
);
};

export const useRegion = () => {
  const context = useContext(RegionContext);

  if (!context) {
    throw new Error(
      "useRegion must be used within a RegionProvider"
    );
  }

  return context;
};
