import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { DollarSign } from "lucide-react";
import { detectCountryFromIP, detectCountryFromTimezone } from "@/lib/ip-geolocation";
import { supabase } from "@/integrations/supabase/client";
import {
  BUILTIN_REGION_OPTIONS,
  mergeRegions,
  mapAllowedRegionRows,
  readRegionCache,
  writeRegionCache,
  resolveRegion,
  type AllowedRegionRow,
} from "@/lib/region-cache";

import {
  getStoredCountry,
  getStoredMode,
  persistCountry,
  persistMode,
} from "@/lib/region-cookie";

/**
 * Regions are no longer a closed set. "USA" and "Nigeria" are the built-in
 * launch regions; every other region is generated by the admin Region Builder
 * (public.region_definitions) and becomes selectable once it is ready or
 * published. The `(string & {})` branch keeps literal autocomplete for the
 * built-ins while allowing any builder-generated country name.
 */
export type Country = "USA" | "Nigeria" | (string & {});
export type RegionMode = "auto" | "manual";
export type Currency = "USD" | "NGN" | (string & {});

export const BUILTIN_COUNTRIES = ["USA", "Nigeria"] as const;

export interface RegionOption {
  /** Canonical country value used across the app (matches region_definitions.country_name). */
  value: Country;
  label: string;
  flag: string;
  countryCode: string;
  currency: Currency;
  currencySymbol: string;
  phonePrefix: string;
  /** True for the two hard-coded launch regions. */
  builtIn: boolean;
}

export interface CompanyInfo {
  companyName: string;
  phone: string;
  phoneRaw: string;
  email: string;
  fullAddress: string;
  address: string;
  city: string;
  state: string;
  country: string;
  postalCode: string;
}

interface RegionConfig {
  currency: Currency;
  currencySymbol: string;
  phonePrefix: string;
  whatsappNumber: string;
  smsNumber: string;
  supportEmail: string;
}

interface RegionContextType {
  country: Country;
  setCountry: (country: Country) => void;
  regionMode: RegionMode;
  setRegionMode: (mode: RegionMode) => void;
  isDetecting: boolean;
  currency: Currency;
  currencySymbol: string;
  phonePrefix: string;
  whatsappNumber: string;
  smsNumber: string;
  supportEmail: string;
  companyInfo: CompanyInfo | null;
  getCurrencyIcon: (className?: string) => React.ReactNode;
  config: RegionConfig;
  /** Built-in regions + every Region Builder region that is ready/published. */
  availableRegions: RegionOption[];
  regionsLoading: boolean;
  /** Freshness of the region list so the UI can flag cached/offline data. */
  regionSync: RegionSyncState;
  /** Force a re-fetch of the allowed-region list (bypasses the offline cache). */
  refreshRegions: () => Promise<void>;
}

export interface RegionSyncState {
  /** Where the currently rendered region list came from. */
  source: "live" | "cache" | "builtin";
  /** Epoch ms of the last successful server sync (null when never synced). */
  lastSyncedAt: number | null;
  /** Cache is older than the TTL, or the last refresh attempt failed. */
  stale: boolean;
  /** Browser reports no connectivity, or the last fetch failed while offline. */
  offline: boolean;
  /** A manual/automatic refresh is currently in flight. */
  refreshing: boolean;


// Base config (currency + phone prefix only). Contact channels — WhatsApp, SMS,
// and support email — are loaded from the admin-managed Regional Contact
// Channels table (public.contact_settings). Empty strings here mean
// "not yet loaded"; consumers should render conditionally.
const regionConfig: Record<string, RegionConfig> = {
  USA: {
    currency: "USD",
    currencySymbol: "$",
    phonePrefix: "+1",
    whatsappNumber: "",
    smsNumber: "",
    supportEmail: "",
  },
  Nigeria: {
    currency: "NGN",
    currencySymbol: "₦",
    phonePrefix: "+234",
    whatsappNumber: "",
    smsNumber: "",
    supportEmail: "",
  },
};

// Built-in launch regions live in region-cache so both the cache layer and the
// provider agree on the guaranteed-available baseline.
export { BUILTIN_REGION_OPTIONS };




const stripPhone = (v: string) => (v || "").replace(/[^\d]/g, "");

const NairaIcon = ({ className }: { className?: string }) => (
  <span className={className} aria-hidden>₦</span>
);

const RegionContext = createContext<RegionContextType | undefined>(undefined);

const SAFE_DEFAULT: Country = "USA";

export const RegionProvider = ({ children }: { children: ReactNode }) => {
  const [isDetecting, setIsDetecting] = useState(false);

  const [regionMode, setRegionModeState] = useState<RegionMode>(
    () => getStoredMode() ?? "auto"
  );

  const [country, setCountryState] = useState<Country>(() => {
    const stored = getStoredCountry();
    if (stored) return stored;
    try {
      return detectCountryFromTimezone();
    } catch {
      return SAFE_DEFAULT;
    }
  });

  /**
   * Switch region. The value is resolved against the allow-list first, then
   * persisted server-side through `set_my_region` so web and mobile read the
   * same source of truth after login. The server re-validates and rejects any
   * region the user is not permitted to select.
   */
  const setCountry = (next: Country) => {
    const resolved = resolveRegion(next, availableRegions);
    if (!resolved) return;
    setCountryState(resolved.value);
    persistCountry(resolved.value);
    try {
      void supabase.rpc("set_my_region", { _country: resolved.value }).then(({ error }) => {
        if (error) console.warn("[region] server rejected region change:", error.message);
      });
    } catch {
      // Offline: the local preference stands and re-syncs on next login.
    }

  };


  const setRegionMode = (next: RegionMode) => {
    setRegionModeState(next);
    persistMode(next);
  };

  // First-load auto detection (IP -> timezone -> safe default)
  useEffect(() => {
    let cancelled = false;
    const run = async () => {
      if (regionMode !== "auto") return;
      setIsDetecting(true);
      try {
        const result = await detectCountryFromIP();
        if (!cancelled && result.detected) {
          setCountryState(result.country);
          persistCountry(result.country);
        }
      } catch {
        // keep timezone/stored/default fallback
      } finally {
        if (!cancelled) setIsDetecting(false);
      }
    };
    run();
    return () => {
      cancelled = true;
    };
  }, [regionMode]);

  // Sync with the signed-in user's profile preference.
  // Owners/drivers (and any non-admin role) are locked to their registration
  // region — their dashboard must not flip when they travel. Only admins and
  // admin assistants may freely switch regions.
  useEffect(() => {
    let cancelled = false;
    const syncProfile = async (userId: string) => {
      try {
        const [{ data: profile }, { data: roles }] = await Promise.all([
          supabase
            .from("profiles")
            .select("preferred_country, region_mode")
            .eq("user_id", userId)
            .maybeSingle(),
          supabase
            .from("user_roles")
            .select("role")
            .eq("user_id", userId),
        ]);
        if (cancelled) return;

        const roleList = (roles ?? []).map((r: { role: string }) => r.role);
        const isAdminLike =
          roleList.includes("admin") || roleList.includes("admin_assistant");

        const pc = (profile?.preferred_country ?? null) as Country | null;
        const rm = (profile?.region_mode ?? null) as RegionMode | null;

        if (!isAdminLike) {
          // Lock to registration region. If profile has no region yet
          // (first sign-in after registration), pin the current detected
          // country as their permanent region.
          let locked: Country | null = pc;
          if (!locked) {
            locked = getStoredCountry() ?? country;
            supabase
              .from("profiles")
              .update({ preferred_country: locked, region_mode: "manual" })
              .eq("user_id", userId)
              .then(() => {});
          }
          setRegionModeState("manual");
          persistMode("manual");
          if (locked) {
            setCountryState(locked);
            persistCountry(locked);
          }
          return;
        }

        // Admins keep their stored preference and switching ability.
        if (rm === "auto" || rm === "manual") {
          setRegionModeState(rm);
          persistMode(rm);
        }
        if (pc && String(pc).trim()) {
          setCountryState(pc);
          persistCountry(pc);
        }

      } catch {
        /* ignore */
      }
    };

    supabase.auth.getUser().then(({ data }) => {
      if (data.user) syncProfile(data.user.id);
    });

    const { data: sub } = supabase.auth.onAuthStateChange((_e, session) => {
      if (session?.user) syncProfile(session.user.id);
    });
    return () => {
      cancelled = true;
      sub.subscription.unsubscribe();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);


  // Persist manual selections back to profile if signed in.
  useEffect(() => {
    if (regionMode !== "manual") return;
    supabase.auth.getUser().then(({ data }) => {
      if (!data.user) return;
      supabase
        .from("profiles")
        .update({ preferred_country: country, region_mode: "manual" })
        .eq("user_id", data.user.id)
        .then(() => {});
    });
  }, [country, regionMode]);

  // ---------------------------------------------------------------------
  // Region Builder regions. The two built-ins are always available; every
  // region generated by the admin Region Builder (public.region_definitions)
  // joins the list as soon as it is ready/published, and updates live.
  // ---------------------------------------------------------------------
  // Seed from the offline cache so an installed PWA renders the correct
  // region list instantly, even with no network.
  const [builderRegions, setBuilderRegions] = useState<RegionOption[]>(
    () => readRegionCache()?.regions.filter((r) => !r.builtIn) ?? [],
  );
  const [regionsLoading, setRegionsLoading] = useState(() => !readRegionCache());


  useEffect(() => {
    let cancelled = false;
    const load = async () => {
      try {
        // Authoritative list comes from the server-side allow-list RPC so the
        // client can never invent a region that admins have not published.
        const { data, error } = await supabase.rpc("get_allowed_regions");
        if (cancelled) return;
        if (error || !data) {
          // Offline / RPC failure → keep whatever the cache gave us (or the
          // built-ins) instead of blanking the picker.
          setRegionsLoading(false);
          return;
        }
        const mapped = mapAllowedRegionRows(data as unknown as AllowedRegionRow[]);
        const merged = mergeRegions(mapped.filter((r) => !r.builtIn));
        setBuilderRegions(merged.filter((r) => !r.builtIn));
        writeRegionCache(merged);
      } catch {
        // Network down or RPC unavailable — cached/built-in regions stand.
      } finally {
        if (!cancelled) setRegionsLoading(false);
      }
    };

    load();
    const channel = supabase
      .channel("region_definitions_available")
      .on(
        "postgres_changes",
        { event: "*", schema: "public", table: "region_definitions" },
        () => load(),
      )
      .subscribe();
    // Realtime can be delayed or unavailable (offline PWA); revalidate on
    // resume and on a slow poll so the list self-heals.
    const onResume = () => {
      if (document.visibilityState === "visible") load();
    };
    document.addEventListener("visibilitychange", onResume);
    window.addEventListener("online", onResume);
    const poll = window.setInterval(load, 10 * 60 * 1000);
    return () => {
      cancelled = true;
      supabase.removeChannel(channel);
      document.removeEventListener("visibilitychange", onResume);
      window.removeEventListener("online", onResume);
      window.clearInterval(poll);
    };
  }, []);

  const availableRegions: RegionOption[] = mergeRegions(builderRegions);


  // Load region-specific WhatsApp / SMS / email from the admin-managed
  // "Regional Contact Channels" table. Falls back to base regionConfig when
  // no active row exists for a channel.
  const [contactOverrides, setContactOverrides] = useState<
    Record<string, Partial<Pick<RegionConfig, "whatsappNumber" | "smsNumber" | "supportEmail">>>
  >({ USA: {}, Nigeria: {} });

  const [companyInfoMap, setCompanyInfoMap] = useState<Record<string, CompanyInfo | null>>({
    USA: null,
    Nigeria: null,
  });

  useEffect(() => {
    let cancelled = false;
    const load = async () => {
      const { data, error } = await supabase
        .from("contact_settings")
        .select("region, contact_type, contact_value, is_active")
        .eq("is_active", true);
      if (cancelled || error || !data) return;
      const next: typeof contactOverrides = { USA: {}, Nigeria: {} };
      for (const row of data as Array<{ region: string; contact_type: string; contact_value: string }>) {
        const region = row.region || "USA";
        next[region] ??= {};
        const value = row.contact_value?.trim() || "";
        if (!value) continue;
        if (row.contact_type === "whatsapp") next[region].whatsappNumber = stripPhone(value);
        else if (row.contact_type === "sms") next[region].smsNumber = stripPhone(value);
        else if (row.contact_type === "email") next[region].supportEmail = value;
      }
      setContactOverrides(next);
    };
    load();
    const channel = supabase
      .channel("contact_settings_changes")
      .on(
        "postgres_changes",
        { event: "*", schema: "public", table: "contact_settings" },
        () => load(),
      )
      .subscribe();
    return () => {
      cancelled = true;
      supabase.removeChannel(channel);
    };
  }, []);

  // Load per-region company info (drives landing footer + admin panel)
  useEffect(() => {
    let cancelled = false;
    const load = async () => {
      const { data, error } = await supabase
        .from("platform_company_info")
        .select("*")
        .eq("is_active", true);
      if (cancelled || error || !data) return;
      const next: Record<string, CompanyInfo | null> = { USA: null, Nigeria: null };
      for (const row of data as Array<Record<string, unknown>>) {
        const region = String(row.region ?? "USA");
        next[region] = {
          companyName: String(row.company_name ?? ""),
          phone: String(row.phone ?? ""),
          phoneRaw: String(row.phone_raw ?? ""),
          email: String(row.email ?? ""),
          fullAddress: String(row.full_address ?? ""),
          address: String(row.address_line ?? ""),
          city: String(row.city ?? ""),
          state: String(row.state ?? ""),
          country: String(row.country_name ?? ""),
          postalCode: String(row.postal_code ?? ""),
        };
      }
      setCompanyInfoMap(next);
    };
    load();
    const channel = supabase
      .channel("platform_company_info_changes")
      .on(
        "postgres_changes",
        { event: "*", schema: "public", table: "platform_company_info" },
        () => load(),
      )
      .subscribe();
    return () => {
      cancelled = true;
      supabase.removeChannel(channel);
    };
  }, []);

  const baseConfig = regionConfig[country] ??
    (() => {
      const built = builderRegions.find((r) => r.value === country);
      return {
        currency: built?.currency ?? "USD",
        currencySymbol: built?.currencySymbol ?? "$",
        phonePrefix: built?.phonePrefix ?? "+1",
        whatsappNumber: "",
        smsNumber: "",
        supportEmail: "",
      } as RegionConfig;
    })();
  const overrides = contactOverrides[country] ?? {};
  const config: RegionConfig = {
    ...baseConfig,
    whatsappNumber: overrides.whatsappNumber || baseConfig.whatsappNumber,
    smsNumber: overrides.smsNumber || baseConfig.smsNumber,
    supportEmail: overrides.supportEmail || baseConfig.supportEmail,
  };

  const getCurrencyIcon = (className = "h-4 w-4") =>
    config.currency === "NGN" ? (
      <NairaIcon className={className} />
    ) : (
      <DollarSign className={className} />
    );

  return (
    <RegionContext.Provider
      value={{
        country,
        setCountry,
        regionMode,
        setRegionMode,
        isDetecting,
        ...config,
        companyInfo: companyInfoMap[country] ?? null,
        getCurrencyIcon,
        config,
        availableRegions,
        regionsLoading,
      }}
    >
      {children}
    </RegionContext.Provider>
  );
};

export const useRegion = () => {
  const context = useContext(RegionContext);
  if (!context) throw new Error("useRegion must be used within a RegionProvider");
  return context;
};
